apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gradle-sample-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gradle-sample-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gradle-sample-app.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}

